//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMIS {
    
    
    public partial class processCheckParametersInput {
        
        /// <summary>
        /// inputProcessCheckParameterScriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager inputProcessCheckParameterScriptManager;
        
        /// <summary>
        /// inputProcessCheckParameterUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel inputProcessCheckParameterUpdatePanel;
        
        /// <summary>
        /// inputProcessCheckParameterWCNameDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList inputProcessCheckParameterWCNameDropDownList;
        
        /// <summary>
        /// inputProcessCheckParameterWCIDLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label inputProcessCheckParameterWCIDLabel;
        
        /// <summary>
        /// inputProcessCheckParameterWorkCenterNameReqFieldValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator inputProcessCheckParameterWorkCenterNameReqFieldValidator;
        
        /// <summary>
        /// inputProcessCheckParameterProductTypeDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList inputProcessCheckParameterProductTypeDropDownList;
        
        /// <summary>
        /// inputProcessCheckParameterProductTypeIDLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label inputProcessCheckParameterProductTypeIDLabel;
        
        /// <summary>
        /// inputProcessCheckParameterProductTyeNameReqFieldValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator inputProcessCheckParameterProductTyeNameReqFieldValidator;
        
        /// <summary>
        /// inputProcessCheckParameterRecipeNameDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList inputProcessCheckParameterRecipeNameDropDownList;
        
        /// <summary>
        /// inputProcessCheckParameterRecipeIDLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label inputProcessCheckParameterRecipeIDLabel;
        
        /// <summary>
        /// inputProcessCheckParameterRecipeNameReqFieldValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator inputProcessCheckParameterRecipeNameReqFieldValidator;
        
        /// <summary>
        /// inputProcessCheckParameterNameDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList inputProcessCheckParameterNameDropDownList;
        
        /// <summary>
        /// inputProcessCheckParameterMasterIDLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label inputProcessCheckParameterMasterIDLabel;
        
        /// <summary>
        /// inputProcessCheckParameterNameDropDownReqFieldValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator inputProcessCheckParameterNameDropDownReqFieldValidator;
        
        /// <summary>
        /// inputProcessCheckParameterValueTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox inputProcessCheckParameterValueTextBox;
        
        /// <summary>
        /// inputProcessCheckParameterIDLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label inputProcessCheckParameterIDLabel;
        
        /// <summary>
        /// inputProcessCheckParameterValueTextBoxReqFieldValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator inputProcessCheckParameterValueTextBoxReqFieldValidator;
        
        /// <summary>
        /// inputProcessCheckParameterDateTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox inputProcessCheckParameterDateTextBox;
        
        /// <summary>
        /// InputCalanderImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image InputCalanderImage;
        
        /// <summary>
        /// RequiredFieldValidator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        
        /// <summary>
        /// inputProcessCheckParameterSaveButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button inputProcessCheckParameterSaveButton;
        
        /// <summary>
        /// inputProcessCheckParameterCancelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button inputProcessCheckParameterCancelButton;
        
        /// <summary>
        /// inputProcessCheckParameterMessageLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label inputProcessCheckParameterMessageLabel;
        
        /// <summary>
        /// inputProcessCheckParameterDialogOKButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button inputProcessCheckParameterDialogOKButton;
        
        /// <summary>
        /// inputProcessCheckParameterDialogCancelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button inputProcessCheckParameterDialogCancelButton;
        
        /// <summary>
        /// inputProcessCheckParameterNotifyTimer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.Timer inputProcessCheckParameterNotifyTimer;
        
        /// <summary>
        /// inputProcessCheckParameterIDHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField inputProcessCheckParameterIDHidden;
        
        /// <summary>
        /// inputProcessCheckParameterNotifyMessageDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl inputProcessCheckParameterNotifyMessageDiv;
        
        /// <summary>
        /// inputProcessCheckParameterNotifyImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage inputProcessCheckParameterNotifyImage;
        
        /// <summary>
        /// inputProcessCheckParameterNotifyLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label inputProcessCheckParameterNotifyLabel;
        
        /// <summary>
        /// inputProcessCheckParameterPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel inputProcessCheckParameterPanel;
        
        /// <summary>
        /// inputProcessCheckParameterGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView inputProcessCheckParameterGridView;
    }
}
